Make main thread actions sequential
24seconds/rust-cli-pomodoro pull request #17
Opened 2021-12-09 19:18 UTC by Pablito2020

As listed in issue: #16, the pomodoro main thread can handle more operations sequentially without the overhead of creating tokio threads.

It should be noted that the CREATE option has  been refactored and moved to a separate method, but it would still be quite necessary a refactor for the whole system (isolating different logics, like for example the DataBase logic has to be completely decoupled from main.rs, the parsing arguments part should be delegated to argument.rs, and so much more) but this has to be thinked and talked in another issue.

In addition, I can say that theoretically this pull request does not break any of the current functionalities of the code (since I have tested the application and it seems to work the same as before), although, as at the moment there are no unit tests, I cannot ensure that this is true for the 100% of cases.

2021-12-10 04:06 UTC, 24seconds commented
[Request]
It seems already merged commits exist, ba6a416 and 
080a0b7. Could you make commit logs clear?

2021-12-10 04:28 UTC, 24seconds commented
[Request]
Could you run this command right under the directory and resolve warning? About `Hint` warning, you can ignore it
```
cargo clippy
```

2021-12-10 05:29 UTC, 24seconds requested changes
Thank you for the work.
Looks good overall

2021-12-10 05:29 UTC, 24seconds commented on src/main.rs
> +                debug!("Message::DeleteAll done");
[Request]
Here we previously make output message, `All notifications deleted` but it seems it's omitted. Could you add this?

2021-12-10 15:09 UTC, Pablito2020 commented
The changes has been made to the branch. I had to do a "git rebase" for deleting the documentation commit and that's why in the pull request now appears: 

_Pablito2020 force-pushed the main-sequential branch from e9c2030 to af68323 1 minute ago_

2021-12-11 13:39 UTC, 24seconds approved these changes
Thank you for addressing feedback! LGTM

2021-12-11 13:39 UTC, 24seconds commented on src/main.rs
> +        // is just a "temporal fix" for returning from the function.
[comment]
Good

2021-12-11 13:39 UTC, 24seconds commented
[Question]
I don't know whether you can merge yourself or not, if you can, please do it!

2021-12-12 11:56 UTC, Pablito2020 commented
> [Question] I don't know whether you can merge yourself or not, if you can, please do it!
I can't merge it to the repository because I don't have write access to it.

2021-12-12 13:02 UTC, 24seconds commented
Aha! Sorry, I didn't know that. Thank you for the check!

2021-12-12 13:02 UTC, merged